In [1]:
import pandas as pd

In [27]:
data=pd.read_csv("./data/data4.csv",delimiter=",")

In [28]:
data.head(n=50)

,sno,name,sex,age,cat,party,symb,genral,postal,total,%age
0,1.0,SHARAD KUMAR,M,40.0,GEN,AAAP,Broom,95887.0,256.0,96143.0,59.97
1,2.0,NEEL DAMAN KHATRI,M,44.0,GEN,BJP,Lotus,54610.0,1241.0,55851.0,34.84
2,3.0,PRAVEEN KUMAR BHUGRA,M,46.0,GEN,INC,Hand,4619.0,24.0,4643.0,2.90
3,4.0,ROOPESH BHARDWAJ,M,40.0,GEN,BSP,Elephant,1648.0,14.0,1662.0,1.04
4,5.0,None of the Above,NaN,NaN,NaN,NOTA,NOTA,764.0,3.0,767.0,0.48
5,6.0,BRIJ MOHAN,M,37.0,GEN,SHS,Bow &,477.0,1.0,478.0,0.30
6,NaN,NaN,NaN,NaN,NaN,NaN,Arrow,NaN,NaN,NaN,NaN
7,7.0,SURENDER,M,48.0,GEN,CPI(ML),Cup &,362.0,1.0,363.0,0.23
8,NaN,NaN,NaN,NaN,NaN,(L),Saucer,NaN,NaN,NaN,NaN
9,8.0,MANOJ KUMAR,M,42.0,GEN,IND,Hat,218.0,0.0,218.0,0.14
10,9.0,AJAY MUDGIL,M,30.0,GEN,IND,Coconut,191.0,0.0,191.0,0.12
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1.0,SANJEEV JHA,M,35.0,GEN,AAAP,Broom,124476.0,248.0,124724.0,63.82
14,2.0,GOPAL JHA,M,46.0,GEN,BJP,Lotus,55988.0,786.0,56774.0,29.05
15,3.0,J S CHAUHAN,M,66.0,GEN,INC,Hand,6683.0,67.0,6750.0,3.45
16,4.0,RAMBIR,M,42.0,SC,BSP,Elephant,2319.0,24.0,2343.0,1.20
17,5.0,MANAGER CHAURASIYA,M,45.0,GEN,SUCI,Battery,929.0,1.0,930.0,0.48
18,NaN,NaN,NaN,NaN,NaN,NaN,Torch,NaN,NaN,NaN,NaN
19,6.0,DHARAM PAL SINGH,M,49.0,GEN,SHS,Bow &,560.0,1.0,561.0,0.29
20,NaN,NaN,NaN,NaN,NaN,NaN,Arrow,NaN,NaN,NaN,NaN
21,7.0,KHADAK LAL,M,63.0,GEN,IND,Auto-,540.0,0.0,540.0,0.28
22,NaN,NaN,NaN,NaN,NaN,NaN,Rickshaw,NaN,NaN,NaN,NaN
23,8.0,RICHA MUNDRA,F,37.0,GEN,SASAPT,Television,531.0,1.0,532.0,0.27
24,9.0,NAFE SINGH RAJPUT,M,41.0,GEN,IND,Brush,435.0,0.0,435.0,0.22
25,10.0,None of the Above,NaN,NaN,NaN,NOTA,NOTA,410.0,3.0,413.0,0.21
26,11.0,PREM SHANKAR SHARMA,M,51.0,GEN,ABSPAR,Pen Stand,382.0,0.0,382.0,0.20
27,NaN,NaN,NaN,NaN,NaN,TY,NaN,NaN,NaN,NaN,NaN
28,12.0,MADHU DIWAKAR,F,45.0,GEN,CPM,"Hammer,",249.0,1.0,250.0,0.13
29,NaN,NaN,NaN,NaN,NaN,NaN,Sickle and,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,Star,NaN,NaN,NaN,NaN
31,13.0,RANJAN KUMAR SINGH,M,29.0,GEN,BAJD,Hat,155.0,3.0,158.0,0.08
32,14.0,SUSHIL KUMAR MISHRA,M,41.0,GEN,ABHM,Coconut,130.0,0.0,130.0,0.07
33,15.0,GULAB SINGHAL,M,39.0,GEN,RAJP,Cauliflowe,110.0,0.0,110.0,0.06
34,NaN,NaN,NaN,NaN,NaN,NaN,r,NaN,NaN,NaN,NaN
35,16.0,RAJBIR SINGH,M,34.0,SC,IND,Gas,108.0,1.0,109.0,0.06
36,NaN,NaN,NaN,NaN,NaN,NaN,Cylinder,NaN,NaN,NaN,NaN
37,17.0,PRAVEN KUMAR,M,26.0,GEN,GAAP,Plate,90.0,15.0,105.0,0.05
38,NaN,NaN,NaN,NaN,NaN,NaN,Containing,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,Food,NaN,NaN,NaN,NaN
40,18.0,PANKAJ KUMAR,M,38.0,GEN,PPGP,Envelope,96.0,0.0,96.0,0.05
41,NaN,AGARAWAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,19.0,KALPANA GUPTA,F,28.0,GEN,RPI(A),Sewing,85.0,0.0,85.0,0.04
43,NaN,NaN,NaN,NaN,NaN,NaN,Machine,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,1.0,PANKAJ PUSHKAR,M,42.0,GEN,AAAP,Broom,64234.0,243.0,64477.0,51.05
46,2.0,RAJNI ABBI,F,52.0,GEN,BJP,Lotus,43460.0,370.0,43830.0,34.70
47,3.0,SURINDER PAL SINGH,M,54.0,GEN,INC,Hand,14572.0,70.0,14642.0,11.59
48,4.0,MANOJ,M,37.0,GEN,BSP,Elephant,583.0,9.0,592.0,0.47
49,5.0,HARJINDER SINGH,M,49.0,GEN,IND,Battery,581.0,0.0,581.0,0.46

In [29]:
data=data[pd.notnull(data["sno"])]

In [30]:
data.head(n=10)

,sno,name,sex,age,cat,party,symb,genral,postal,total,%age
0,1.0,SHARAD KUMAR,M,40.0,GEN,AAAP,Broom,95887.0,256.0,96143.0,59.97
1,2.0,NEEL DAMAN KHATRI,M,44.0,GEN,BJP,Lotus,54610.0,1241.0,55851.0,34.84
2,3.0,PRAVEEN KUMAR BHUGRA,M,46.0,GEN,INC,Hand,4619.0,24.0,4643.0,2.90
3,4.0,ROOPESH BHARDWAJ,M,40.0,GEN,BSP,Elephant,1648.0,14.0,1662.0,1.04
4,5.0,None of the Above,NaN,NaN,NaN,NOTA,NOTA,764.0,3.0,767.0,0.48
5,6.0,BRIJ MOHAN,M,37.0,GEN,SHS,Bow &,477.0,1.0,478.0,0.30
7,7.0,SURENDER,M,48.0,GEN,CPI(ML),Cup &,362.0,1.0,363.0,0.23
9,8.0,MANOJ KUMAR,M,42.0,GEN,IND,Hat,218.0,0.0,218.0,0.14
10,9.0,AJAY MUDGIL,M,30.0,GEN,IND,Coconut,191.0,0.0,191.0,0.12
13,1.0,SANJEEV JHA,M,35.0,GEN,AAAP,Broom,124476.0,248.0,124724.0,63.82